---
title: "Week2_Day1_QC"
format: html
editor: visual
---

## Load libraries to confirm installation

```{r}
library(Rqc) 
library(fastqcr) 
library(QuasR) 
library(ShortRead) 
library(ggplot2)
print("All Bioconductor packages loaded successfully!")
```

```{r}
# Setup knitr options for the report generation
# This ensures that even in a non-interactive environment, 
# the automated report renders successfully.
knitr::opts_chunk$set(
  eval = TRUE,
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

# Generate the HTML report
# By specifying an outdir, we tell Rqc exactly where to put the results
dir.create("Rqc_Full_Report")
reportFile <- rqcReport(qc_result, outdir = "Rqc_Full_Report")
```

```{r}
# Define the path to the directory containing the example fastq files
fastq_dir <- system.file(package="ShortRead", "extdata/E-MTAB-1147")
fastq_dir

# Run the QC analysis on ALL .fastq.gz files in that directory
qc_result <- rqc(path = fastq_dir, pattern = ".fastq.gz", openBrowser=FALSE)
qc_result
```

```{r}
rqcReadQualityBoxPlot(qc_result)
```

```{r}
p_avg <- rqcReadQualityBoxPlot(qc_result) + 
  geom_hline(yintercept = 30, color = "green", linetype = "dashed")

p_avg


ggsave("average_quality.png", plot = p_avg)

```

```{r}
rqcCycleQualityBoxPlot(qc_result)
```

```{r}
p_qual <- rqcCycleQualityBoxPlot(qc_result) +
  geom_hline(yintercept = 30, color = "green", linetype = "dashed")

p_qual

ggsave("quality_boxplot.png", plot = p_qual)
```

```{r}
rqcCycleBaseCallsLinePlot(qc_result)
```

```{r}
p_base <- rqcCycleBaseCallsLinePlot(qc_result)

ggsave("base_content_plot.png", plot = p_base)
```

```{r}
rqcReadFrequencyPlot(qc_result)
```

```{r}
p_freq <- rqcReadFrequencyPlot(qc_result)

ggsave("read_frequency.png", plot = p_freq)

```

If I saw a massive spike at the far right of this plot, I would be more worried about PCR Bias
